### ISSUE TITLE
Integration with a tornado application

### ISSUE THREAD

**Issue by connessionetech** [rocketgram/rocketgram#3]
Hello,

Thank you for creating this. I would like to know how to add the bot to my existing python tornado application. I did not see any tornado-based examples so created this issue.

Regards

**Comment by vd2org** [comment]
In general I don't recommend that you do this.

`Rocketgram` is a stateful application while regular web-app aims to be stateless. This means only one instance of the application must be started. Otherwise your bot will not work properly and you will get unexpected side-effects.

But if you know what you doing you can create regular endpoint, manual set up webhook and then transfer all requests to the Bot object like I did in `TornadoExecutor`.

Sorry for the delay in answering.
